### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of undefined Jset

### ISSUE THREAD

**Issue by mnob2019** [namespace-ee/react-calendar-timeline#789]
Hi, probably someone had this problem, I have an issue with using Jest and shallow rendering. It returns me the following error:
May be someone bumped into this issue somehow  it seems that basically this4.container is undefined....for some reasons ...

  TypeError: Cannot read property 'getBoundingClientRect' of undefined

      189 | 
      190 |       let timeline;
    > 191 |       timeline=shallow(<Timeline  groups={groups} items={items} sidebarWidth={150} rightSidebarWidth={150} visibleTimeStart={visibleTimeStart} visibleTimeEnd={visibleTimeEnd} />)
          |                ^
      192 |       console.log(timeline)
      193 |       
      194 |       

      at ReactCalendarTimeline.resize (node_modules/react-calendar-timeline/lib/lib/Timeline.js:122:51)
      at ReactCalendarTimeline.componentDidMount (node_modules/react-calendar-timeline/lib/lib/Timeline.js:478:12)
      at fn (node_modules/enzyme/src/ShallowWrapper.js:429:22)
      at Object.batchedUpdates (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:781:16)
      at new ShallowWrapper (node_modules/enzyme/src/ShallowWrapper.js:428:26)
      at shallow (node_modules/enzyme/src/shallow.js:10:10)
      at Object.<anonymous> (src/__tests__/CalendarAdmin.test.js:191:16)

**Comment by developer-ocansey** [comment]
Closing as part of issue triage. This issue was created before 2023 and has had no recent activity. If you're still experiencing this on v0.30+, please open a new issue with a minimal reproduction.
